name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          sonar-project-key: el_teu_projecte_key
          sonar-project-name: el_teu_projecte_nom
          sonar-project-version: 1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
