name: SonarQube tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with javac
        run: |
          mkdir -p out
          javac -d out $(find src/main/java -name "*.java")

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          args: -Dsonar.projectBaseDir=${{ github.workspace }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
